spring:
  rabbitmq:
    host: 1.14.157.131
    username: admin
    password: 820606

  application:
    name: config-client
  config:
    import: optional:configserver:http://localhost:3344
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: config
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 2
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
server:
  port: 3355



