spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.157.131:3306/mybatis
    username: uog
    password: 820606
  rabbitmq:
    host: 1.14.157.131
    username: admin
    password: 820606
  redis:
    host: 1.14.157.131
    password: 820606
  application:
    name: 'cloud-provider-payment'
  cloud:
    zookeeper:
      connect-string: 1.14.157.131:2181




mybatis-plus:
  mapper-locations: classpath:/mybatisPlus/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8004



