server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -
         id: "payment_routh"
         uri: "lb://CLOUD-PROVIDER-PAYMENT"
         predicates:
           - 'Path=/selectPayment/**,/selectPay/** '
         filters:
           - 'AddRequestParameter=red, blue'











eureka:
  instance:
    instance-id: payment1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 2
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka


