server:
  port: 2001

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8719
  datasource:
    username: uog
    password: 820606
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.157.131:3306/seata_order
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 400000
        readTimeout: 400000
        loggerLevel: FULL




management:
  endpoints:
    sentinel:
      enable: true
    web:
      exposure:
        include: '*'
mybatis-plus:
  mapper-locations: classpath:/mybatisPlus/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.seataorderservice2001.server.OrderService: debug
    com.seataorderservice2001.server.AccountService: debug
    com.seataorderservice2001.server.StorageService: debug
    io:
      seata: info

seata:
  registry:
    nacos:
      server-addr: 1.14.157.131:8848
      application: seata-server
      username: nacos
      password: nacos
      group: "SEATA_GROUP"
      cluster: default
    type: nacos
  config:
    nacos:
     server-addr: 1.14.157.131:8848
     group: "SEATA_GROUP"
     username: "nacos"
     password: "nacos"
     #data-id: seataServer.properties
    type: nacos
  tx-service-group: seata-order-service2001




